name: Hello World Action

# Trigger the workflow manually or on every push to the main branch
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  hello-world-job:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Check out the repository code
      - name: Check out code
        uses: actions/checkout@v3
        
      # Step 2: Print "Hello, World!"
      - name: Print Hello World
        run: echo "Hello, World!"

